### ISSUE TITLE
Docs: Unsure about meaning of "Ensure your aws credentials are setup"

### ISSUE THREAD

**Issue by jaller94** [basset/basset#39]
https://github.com/basset/basset/blame/741fb85ac9fdb55dc4d5691589862d1eaa9069f2/docs/aws.md#L20

Could you provide an AWS Docs link that describes how to set up credentials?
Does that already mean to order a server? Do I just need a login to AWS? I am not sure when this step is complete?

P.S. "setup" (or "set-up") is the noun, "set up" the verb

**Comment by jaller94** [comment]
Furthermore, it's unclear which minimal permissions the AWS user needs to perform the actions.

**Comment by jagonalez** [comment]
I'll add a link to: https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-environment.html

the other option is to use aws-vault: https://github.com/99designs/aws-vault

The minimal permissions for packer are found here: https://www.packer.io/docs/builders/amazon.html

for terraform I'll have to look into it, it's likely to be a long list since it creates everything needed to host basset

**Comment by jagonalez** [comment]
fixed in #49
