### ISSUE TITLE
Steps missing in AWS guide

### ISSUE THREAD

**Issue by jaller94** [basset/basset#68]
## Prerequisites
* It's unclear whether I have to create the two S3 buckets myself or if the terraform script will do that.
* It's unclear that I had to own a domain on AWS Route53.
  * It's unclear whether I could have used a `basset.` sub domain of a domain managed on a provider other than AWS.
* Because of the above, it's unclear whether I have to create anything else in AWS (e.g. SQS queues) before running terraform.

## Unexplained variables
Steps 3, 6 and 7 ask you to "update" a file. Most variables in these files would benefit from a description.
* Is `user_password` in `infrastructure/packer/vars.json` a password for the first user in Basset or for Basset to send emails via SMTP?
* Which values do I have to change in `infrastructure/terraform/userdata.tpl`?
  * `BASSET_SECRET` is supposed to be a random string, right?
  * `DB_PASSWORD` has to match `db_password` from `infrastructure/packer/vars.json`, right?
* Which values do I have to change in `infrastructure/terraform/terraform.tfvars`?
  * What are the variables `ecr_name`, `compute_name`, `batch_queue_name`, `definition_name`, `key_name` used for? Can I just leave them untouched? If not, what values are expected?

**Comment by jagonalez** [comment]
There are terraform scripts for creating all the resources basset needs. You'll need some understanding of Terraform in order to configure it.

If you run `terraform plan` it will give you a list of the resources it creates, or you can check `infrastructure/terraform/` to see the resources that are created

`user_password` and `user_email` are used to create a user. Since basset can run in "private" mode you cannot create a user unless you do so from the ec2 instance.
`db_password` must match `DB_PASSWORD`
here's where they're used: https://github.com/basset/basset/blob/master/infrastructure/playbook/roles/basset/tasks/main.yml#L198
DB_USERNAME in this instance is `basset` so I'll need to fix that

for `infrastructure/terraform/userdata.tpl`:
`BASSET_SECRET` - yes a secret be generated running `node express/commands/generate-secret.js`

`infrastructure/terraform/terraform.tfvars` :`cr_name, compute_name, batch_queue_name, definition_name, key_name` can be left as they are - they are the resource names for the respective resources created
